### ISSUE TITLE
[BUG] interaction on a custom block

### ISSUE THREAD

**Issue by Walabise** [Asleeepp/skript-itemsadder#15]
**Describe the bug**
When I perform an interaction on a custom block, an error is displayed in the console.
I would just like to replace the custom block with air

```
[19:30:51] [Server thread/ERROR]: #!#! 
[19:30:51] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[19:30:51] [Server thread/ERROR]: #!#! An error occurred while trying to load a Structure.
[19:30:51] [Server thread/ERROR]: #!#! 
[19:30:51] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[19:30:51] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[19:30:51] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[19:30:51] [Server thread/ERROR]: #!#! Here is full list of them:
[19:30:51] [Server thread/ERROR]: #!#! skript-placeholders v1.6.0 (https://github.com/APickledWalrus/skript-placeholders) skript-citizens v1.0.0 ItemsAdder v3.6.3-beta-13 (devs.beer) skript-itemsadder v1.5 
[19:30:51] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[19:30:51] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[19:30:51] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[19:30:51] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[19:30:51] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[19:30:51] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[19:30:51] [Server thread/ERROR]: #!#! 
[19:30:51] [Server thread/ERROR]: #!#! Stack trace:
[19:30:51] [Server thread/ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because "<parameter2>" is null
[19:30:51] [Server thread/ERROR]: #!#!     at ItemsAdder_3.6.3-beta-13.jar//dev.lone.itemsadder.api.CustomStack.<init>(SourceFile:35)
[19:30:51] [Server thread/ERROR]: #!#!     at ItemsAdder_3.6.3-beta-13.jar//dev.lone.itemsadder.api.CustomStack.<init>(SourceFile:29)
[19:30:51] [Server thread/ERROR]: #!#!     at ItemsAdder_3.6.3-beta-13.jar//dev.lone.itemsadder.api.CustomBlock.<init>(SourceFile:35)
[19:30:51] [Server thread/ERROR]: #!#!     at ItemsAdder_3.6.3-beta-13.jar//dev.lone.itemsadder.api.CustomBlock.getOriginal(SourceFile:57)
[19:30:51] [Server thread/ERROR]: #!#!     at ItemsAdder_3.6.3-beta-13.jar//dev.lone.itemsadder.api.CustomBlock.getInstance(SourceFile:66)
[19:30:51] [Server thread/ERROR]: #!#!     at skript-itemsadder-1.5.jar//me.asleepp.SkriptItemsAdder.elements.types.Types$1.parse(Types.java:40)
[19:30:51] [Server thread/ERROR]: #!#!     at skript-itemsadder-1.5.jar//me.asleepp.SkriptItemsAdder.elements.types.Types$1.parse(Types.java:26)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.registrations.Classes.parseSimple(Classes.java:481)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:588)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:771)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:162)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:157)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:62)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1293)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:232)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.Statement.parse(Statement.java:59)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:945)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.Section.loadCode(Section.java:89)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:237)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.Section.init(Section.java:68)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:259)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:178)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:211)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.Section.parse(Section.java:177)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:965)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.SkriptEvent.load(SkriptEvent.java:116)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.structures.StructEvent.load(StructEvent.java:73)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$8(ScriptLoader.java:566)
[19:30:51] [Server thread/ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1755)
[19:30:51] [Server thread/ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1743)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$10(ScriptLoader.java:558)
[19:30:51] [Server thread/ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
[19:30:51] [Server thread/ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
[19:30:51] [Server thread/ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:511)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:457)
[19:30:51] [Server thread/ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:190)
[19:30:51] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:30:51] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[19:30:51] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1013)
[19:30:51] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[19:30:51] [Server thread/ERROR]: #!#!     at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.a(ExecuteCommand.java:32)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.commands.execution.UnboundEntryAction.a(UnboundEntryAction.java:8)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.commands.execution.ExecutionContext.a(ExecutionContext.java:101)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:442)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:344)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:331)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2301)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$15(PlayerConnection.java:2261)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[19:30:51] [Server thread/ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1498)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1475)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1398)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1376)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1265)
[19:30:51] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[19:30:51] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[19:30:51] [Server thread/ERROR]: #!#! 
[19:30:51] [Server thread/ERROR]: #!#! Version Information:
[19:30:51] [Server thread/ERROR]: #!#!   Skript: 2.8.6 (latest)
[19:30:51] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[19:30:51] [Server thread/ERROR]: #!#!     Date: 15:29:23.319558700
[19:30:51] [Server thread/ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[19:30:51] [Server thread/ERROR]: #!#!   Minecraft: 1.20.4
[19:30:51] [Server thread/ERROR]: #!#!   Java: 21.0.3 (Java HotSpot(TM) 64-Bit Server VM 21.0.3+7-LTS-152)
[19:30:51] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.15.107-2-pve
[19:30:51] [Server thread/ERROR]: #!#! 
[19:30:51] [Server thread/ERROR]: #!#! Server platform: Paper
[19:30:51] [Server thread/ERROR]: #!#! 
[19:30:51] [Server thread/ERROR]: #!#! Current node: set block at location of player's target block to air (WR_Archeo.sk, line 15)
[19:30:51] [Server thread/ERROR]: #!#! Current item: null
[19:30:51] [Server thread/ERROR]: #!#! 
[19:30:51] [Server thread/ERROR]: #!#! Thread: Server thread
[19:30:51] [Server thread/ERROR]: #!#! 
[19:30:51] [Server thread/ERROR]: #!#! Language: french
[19:30:51] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[19:30:51] [Server thread/ERROR]: #!#! 
[19:30:51] [Server thread/ERROR]: #!#! End of Error.
[19:30:51] [Server thread/ERROR]: #!#! 
```

**Server Version (/version):**
 - Purpur 1.20.4

**Skript and skript-itemadder version: v3.6.3-beta-13**
 - Skript:  Skript: 2.8.6 (latest)
 - skript-itemsadder: skript-itemsadder v1.5
 
```on interact with ia block "worldrealms_enchant:strata_stage_1":
    if player's tool is a custom item "archeology_brush":
        replace ia block "worldrealms_enchant:strata_stage_2" at location of player's target block

on interact with ia block "worldrealms_enchant:strata_stage_2":
    if player's tool is a custom item "archeology_brush":
        replace ia block "worldrealms_enchant:strata_stage_3" at location of player's target block

on interact with ia block "worldrealms_enchant:strata_stage_3":
    if player's tool is a custom item "archeology_brush":
        replace ia block "worldrealms_enchant:strata_stage_4" at location of player's target block

on interact with ia block "worldrealms_enchant:strata_stage_4":
    if player's tool is a custom item "archeology_brush":
        set {_loc} to location of event-block
        wait 1 ticks
        set event-block to air
        drop 1 paper with custom model data 10518 at location of player's target block```

**Comment by Asleeepp** [comment]
Yeah, the replace effects are really poorly done and I didn't do a great job at the syntax for them. I'll revamp this effect next update.

**Comment by Walabise** [comment]
So is there a way while waiting for the update?

> Yeah, the replace effects are really poorly done and I didn't do a great job at the syntax for them. I'll revamp both effects next update.

So is there a way while waiting for the update?

**Comment by Asleeepp** [comment]
> So is there a way while waiting for the update?

mmm, you could try setting the block to air using the actual Skript syntax, and then re-setting the block with skript-itemsadder, but if that doesn't work. You'll have to wait unfortunately.

**Comment by Walabise** [comment]
It does not work. Itemsadder must block this, because I can't replace the block with air or another block... I'll wait. Without being too demanding, how long can it take?

**Comment by Asleeepp** [comment]
its a pretty big update, so its going to take a little while

**Comment by Walabise** [comment]
> its a pretty big update, so its going to take a little while

Hello, I would like to remind you about the next fix. I would like to have a fix on the bug...

Good luck!

**Comment by Asleeepp** [comment]
> > its a pretty big update, so its going to take a little while
> 
> Hello, I would like to remind you about the next fix. I would like to have a fix on the bug...
> 
> Good luck!

Sorry for the long wait, I've been hard at working doing school stuff and I haven't been focusing my time on the addon. It should be almost done though :)

**Comment by Walabise** [comment]
> > > its a pretty big update, so its going to take a little while
> > 
> > 
> > Hello, I would like to remind you about the next fix. I would like to have a fix on the bug...
> > Good luck!
> 
> Sorry for the long wait, I've been hard at working doing school stuff and I haven't been focusing my time on the addon. It should be almost done though :)

Hello, do you have any news regarding the new update?
