### ISSUE TITLE
[BUG] Error Disable Plugin for 1.21.1-PAPER

### ISSUE THREAD

**Issue by Lennord** [Asleeepp/skript-itemsadder#18]
**Describe the bug**
When the plugin deactivates it gives me an error below.

Error Disable Plugin for Stop Server:

```
[18:38:53 INFO]: [skript-itemsadder] Disabling skript-itemsadder v1.6
[18:38:53 ERROR]: Error occurred while disabling skript-itemsadder v1.6
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.validate(CraftScheduler.java:539) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:243) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:239) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:190) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:159) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at org.bukkit.scheduler.BukkitRunnable.runTaskAsynchronously(BukkitRunnable.java:63) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at skript-itemsadder-1.6.jar/me.asleepp.SkriptItemsAdder.aliases.AliasesGenerator.saveAliasesToFile(AliasesGenerator.java:67) ~[skript-itemsadder-1.6.jar:?]
	at skript-itemsadder-1.6.jar/me.asleepp.SkriptItemsAdder.aliases.AliasesGenerator.saveAliases(AliasesGenerator.java:157) ~[skript-itemsadder-1.6.jar:?]
	at skript-itemsadder-1.6.jar/me.asleepp.SkriptItemsAdder.SkriptItemsAdder.onDisable(SkriptItemsAdder.java:105) ~[skript-itemsadder-1.6.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:161) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:97) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:541) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:610) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1045) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:847) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1351) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**To Reproduce**
1. Stop Server
2. Error

**Expected behavior**

**Screenshots**
NONE

**Server Version (/version):**
```
[18:40:53 INFO]: Checking version, please wait...
[18:40:53 INFO]: This server is running Paper version 1.21.1-131-ver/1.21.1@84281ce (2024-10-31T17:43:44Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.20.6-151-a4f0f5c (MC: 1.20.6)
```

**Skript and skript-itemadder version:**
 - Skript: 2.9.4
 - skript-itemsadder: 4.0.3
 

**Additional context**
This problem is not significant but I would like it to be corrected as quickly as possible.

**Comment by Asleeepp** [comment]
Is this happening when the plugin is disabling normally, or disabling due to some other reason? (dependencies not installed, etc)

**Comment by Lennord** [comment]
> Is this happening when the plugin is disabling normally, or disabling due to some other reason? (dependencies not installed, etc)

This only happens when it deactivates, because I have all the addons/plugins useful for ItemAdder.
