### ISSUE TITLE
[BUG] Skript unable to load itemsadder lines

### ISSUE THREAD

**Issue by YonioTheNacho** [Asleeepp/skript-itemsadder#19]
**Describe the bug**
Whenever I use any of the lines found in the documentation of the latest version of skript-itemsadder, there is a console text dump and none of the lines work whatsoever

**To Reproduce**
1. Install skript-itemsadder 1.6.1
2. Use the following skript code:
on interact with ia furniture "rpitems:paperwallclosed":
	send "a" to player
	place ia furniture "rpitems:paperwallopen" at event-furniture's location
4. Nothing happens when interacting with said furniture

**Expected behavior**
The closed furniture piece should be replaced by the open one

**Screenshots**

**Server Version (/version):**
 - 1.20.6-148-ver/1.20.6@20f5165 (2024-07-02T15:37:33Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
 
**Skript and skript-itemadder version:**
 - Skript: 2.9.2
 - skript-itemsadder: 1.6.1
 - ItemsAdder: 4.0.2-beta-release-12
 
**Additional context**
Below is the full Skript file
```
on interact with ia furniture "rpitems:paperwallclosed":
	place ia furniture "rpitems:paperwallopen" at event-furniture's location

on interact with ia furniture "rpitems:paperwallopen":
	place ia furniture "rpitems:paperwallclosed" at event-furniture's location
```

Below is a copy-paste of the console message dump

```
30/11 15:27:34 [Error] #!#!
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! [Skript] Severe Error:
30/11 15:27:34 [Error] #!#!
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! Something went horribly wrong with Skript.
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! Here is full list of them:
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! skript-placeholders v1.7.0 (https://github.com/APickledWalrus/skript-placeholders) ItemsAdder v4.0.2-beta-release-12 (devs.beer) SkBee v3.6.1 (https://github.com/ShaneBeee/SkBee) skript-itemsadder v1.6.1 DiscordSRV v1.28.0 (https://github.com/DiscordSRV/DiscordSRV) CosmeticsCoreBridge v1.0.1 BetonQuest v2.1.3 (https://www.betonquest.org/)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#!
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! Stack trace:
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "itemsadder.m.kh.gF()" because "<parameter2>" is null
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at ItemsAdder_4.0.2-beta-release-12.jar//dev.lone.itemsadder.api.CustomStack.<init>(SourceFile:35)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at ItemsAdder_4.0.2-beta-release-12.jar//dev.lone.itemsadder.api.CustomStack.<init>(SourceFile:29)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at ItemsAdder_4.0.2-beta-release-12.jar//dev.lone.itemsadder.api.CustomBlock.<init>(SourceFile:42)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at ItemsAdder_4.0.2-beta-release-12.jar//dev.lone.itemsadder.api.CustomBlock.getOriginal(SourceFile:64)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at ItemsAdder_4.0.2-beta-release-12.jar//dev.lone.itemsadder.api.CustomBlock.getInstance(SourceFile:73)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at skript-itemsadder-1.6.1.jar//me.asleepp.SkriptItemsAdder.util.Util.getCustomBlockId(Util.java:57)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at skript-itemsadder-1.6.1.jar//me.asleepp.SkriptItemsAdder.elements.effects.furniture.EffPlaceCustomFurniture.execute(EffPlaceCustomFurniture.java:59)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at Skript-2.9.2.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at Skript-2.9.2.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at Skript-2.9.2.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at Skript-2.9.2.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at Skript-2.9.2.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:345)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at Skript-2.9.2.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:304)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at Skript-2.9.2.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:315)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at Skript-2.9.2.jar//ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:250)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at net.minecraft.commands.Commands.performCommand(Commands.java:355)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at net.minecraft.commands.Commands.performCommand(Commands.java:342)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at net.minecraft.commands.Commands.performCommand(Commands.java:337)
30/11 15:27:34 [Error] #!#! at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at net.minecraft.server.TickTask.run(TickTask.java:18)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195)
30/11 15:27:34 [Error] #!#! at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488)
30/11 15:27:34 [Error] #!#! at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411)
30/11 15:27:34 [Error] #!#! at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377)
30/11 15:27:34 [Error] #!#! at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238)
30/11 15:27:34 [Error] #!#! at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! at java.base/java.lang.Thread.run(Thread.java:1583)
30/11 15:27:34 [Error] #!#!
30/11 15:27:34 [Error] #!#! Version Information:
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! Skript: 2.9.2
30/11 15:27:34 [Error] #!#! Flavor: skriptlang-github
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! Date: 14:35:57.106583600
30/11 15:27:34 [Error] #!#! Bukkit: 1.20.6-R0.1-SNAPSHOT
30/11 15:27:34 [Error] #!#! Minecraft: 1.20.6
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! Java: 21.0.4 (OpenJDK 64-Bit Server VM 21.0.4+7-LTS)
30/11 15:27:34 [Error] #!#! OS: Linux amd64 5.15.0-125-generic
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#!
30/11 15:27:34 [Error] #!#! Server platform: Paper
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#!
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! Current node: null
30/11 15:27:34 [Error] #!#! Current item: (set|place) [custom] (ia|itemsadder) furniture "rpitems:paperwallopen" at the location of (the player >> ch.njol.skript.classes.data.DefaultConverters$$Lambda/0x00007f1171836ba0@73e5095b: ConverterInfo{from=interface org.bukkit.entity.Entity,to=class org.bukkit.Location,converter=ch.njol.skript.classes.data.DefaultConverters$$Lambda/0x00007f1171836ba0@73e5095b,flags=4})
30/11 15:27:34 [Error] #!#! Current trigger: command /testblock (simple event) (customdoors.sk, line 2)
30/11 15:27:34 [Error] #!#!
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! Thread: Server thread
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#!
30/11 15:27:34 [Error] #!#! Language: english
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! Link parse mode: DISABLED
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#!
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#! End of Error.
30/11 15:27:34 [Error] [14:27:34 ERROR]: #!#!
```

**Comment by Asleeepp** [comment]
> @Asleeepp Can you fix this please?

Will be fixed 👍
